stages:
  prepare:
    cmd: python scripts/data_cleaning.py
    deps:
      - data/raw/MachineLearningRating_v3.txt
    outs:
      - data/processed/insurance_data_clean.csv
  train:
    cmd: python scripts/modeling.py
    deps:
      - data/processed/insurance_data_clean.csv
    outs:
      - models/xgboost_model.json
