name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install dvc[gs] jupyter nbconvert

    - name: Pull data with DVC
      run: |
        dvc config core.no_scm true
        dvc pull

    - name: Run EDA Notebook (Task 1)
      run: |
        jupyter nbconvert --to notebook --execute notebooks/task1_eda.ipynb --output executed_task1.ipynb

    - name: Run Hypothesis Testing Notebook (Task 3)
      run: |
        jupyter nbconvert --to notebook --execute notebooks/task3_Hypothesis_Testing.ipynb --output executed_task3.ipynb

    - name: Run Predictive Modeling Notebook (Task 4)
      run: |
        jupyter nbconvert --to notebook --execute notebooks/task4_Predictive_Modeling.ipynb --output executed_task4.ipynb
